Repository Insideouuut/Insideouuut_backend, pull requests merged in 2024-08, with the labels that each got.

#53 닉네임 중복 확인 오류수정
  Inside-Out/src/main/java/com/goorm/insideout/user/controller/UserJoinController.java
Labels: 🐞 Bug

#59 매너온도. 사용자 신고, 사용자 좋아요 기능 구현
  Inside-Out/src/main/java/com/goorm/insideout/report/controller/ReportController.java
  Inside-Out/src/main/java/com/goorm/insideout/report/domain/Report.java
  Inside-Out/src/main/java/com/goorm/insideout/report/dto/ReportRequest.java
  Inside-Out/src/main/java/com/goorm/insideout/report/repository/ReportRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/report/service/ReportService.java
  Inside-Out/src/main/java/com/goorm/insideout/user/domain/User.java
  Inside-Out/src/main/java/com/goorm/insideout/user/service/UserJoinService.java
Labels: ✨ Feature

#69 fix: User 엔티티 일부 필드 제거
  Inside-Out/src/main/java/com/goorm/insideout/user/domain/User.java
Labels: 🐞 Bug, 🚑 Emergency

#70 fix: User 엔티티 일부 필드 제거
  Inside-Out/src/main/java/com/goorm/insideout/user/domain/User.java
Labels: 🐞 Bug, 🚑 Emergency

#72 feat: Swagger UI가 HTTPS 요청을 받을 수 있도록 설정 추가
  Inside-Out/src/main/java/com/goorm/insideout/global/config/SwaggerConfig.java
Labels: 🚑 Emergency, ✨ Feature

#80 Refactor/채팅 쿼리 개선 #79
  Inside-Out/src/main/java/com/goorm/insideout/chat/repository/ChatRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/repository/custom/ChatQueryDslRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/repository/custom/ChatQueryDslRepositoryImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/userchatroom/repository/UserChatRoomRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/userchatroom/service/UserChatRoomService.java
Labels: ♻️ Refactor

#87 유저 프로필 구현
  Inside-Out/src/main/java/com/goorm/insideout/auth/config/SecurityConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/image/service/ImageService.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/repository/MeetingUserRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/service/MeetingService.java
  Inside-Out/src/main/java/com/goorm/insideout/user/controller/UserProfileController.java
  Inside-Out/src/main/java/com/goorm/insideout/user/dto/request/ProfileUpdateRequest.java
  Inside-Out/src/main/java/com/goorm/insideout/user/dto/response/ProfileMeetingResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/user/dto/response/ProfileResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/user/repository/UserRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/user/service/UserProfileService.java
Labels: ✨ Feature

#97 모임 검색 API 에러 수정
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/response/MeetingResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/search/controller/SearchController.java
Labels: 🐞 Bug

#98 모임 검색 API 에러 수정건 배포
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/response/MeetingResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/search/controller/SearchController.java
Labels: 🐞 Bug

#99 동아리 APi 관련 변경사항 배포
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubUserController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubBoardDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubDetailOwnerDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubDetailUserDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubMemberDetail.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubUserDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubApplyResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubBoardResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubMembersResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubModifyResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Club.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubApply.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubUser.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubApplyRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubUserRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubApplyServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/global/Initializer/DatabaseInitializer.java
  Inside-Out/src/main/java/com/goorm/insideout/image/domain/ProfileImage.java
  Inside-Out/src/main/java/com/goorm/insideout/image/repository/ProfileImageRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/controller/MeetingController.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/response/MeetingResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/service/MeetingService.java
  Inside-Out/src/main/java/com/goorm/insideout/user/domain/User.java
  Inside-Out/src/main/java/com/goorm/insideout/user/repository/UserRepository.java
Labels: 🐞 Bug, ✨ Feature

#101 fix: 동아리 게시판관련 버그수정 및 컨트롤러에 스웨거 적용
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubCommentController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubPostController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubUserController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubBoardResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubCommentService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubCommentServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubServiceImpl.java
Labels: 🐞 Bug

#104 fix: 동아리 수정시 채팅방관련 변수가 누락되던 버그 수정
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubServiceImpl.java
Labels: 🐞 Bug

#106 #105 동아리 변수 테이블 생성 및 그에따른 지원 로직 수정
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubPostController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubBoardResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubListResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Category.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Club.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/GenderRatio.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Level.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubApplyServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserServiceImpl.java
Labels: ✨ Feature

#119 동아리 게시글 Response DTO가 이미지 정보를 반환하도록 추가
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubPostController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubPostDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/controller/MeetingController.java
Labels: ✨ Feature

#120 동아리 게시글 Response DTO가 이미지 정보를 반환건 배포
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubPostController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubPostDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/controller/MeetingController.java
Labels: ✨ Feature

#122 Refactor/동아리 관련 기능들 리팩토링 #109
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubUserController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubApplyResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubMembersResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubPostListResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Club.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubApply.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubComment.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubPost.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubUser.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubUserRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubApplyServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubCommentServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserServiceImpl.java
Labels: ♻️ Refactor

#123 동아리 멤버 확인 및 호스트 확인 로직 구현
  Inside-Out/src/main/java/com/goorm/insideout/auth/config/SecurityConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/chatroom/domain/ChatRoom.java
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubUserController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubMembersResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubUserAuthorityResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubUser.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/controller/MeetingController.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/controller/MeetingUserController.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/domain/Meeting.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/domain/Role.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/response/MeetingUserAuthorityResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/response/MeetingUserResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/repository/MeetingUserRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/service/MeetingApplyService.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/service/MeetingService.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/service/MeetingUserService.java
Labels: ✨ Feature

#136 Feat/동아리 지원시 질문 답변 관계 생성 및 멤버목록에 변수 추가 #135
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubCommentController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubUserController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/AnswerDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubPostDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubApplyRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubApplyResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubMembersResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubPostListResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubQuestionAnswerResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Club.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubApply.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubPost.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubQuestionAnswer.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubUser.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubQuestionAnswerRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubApplyService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubApplyServiceImpl.java
Labels: ✨ Feature

#147 동아리 게시글 조회 오류 수정
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubPostController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubPostRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostServiceImpl.java
Labels: 🐞 Bug, 🚑 Emergency

#150 feat: 포스트 목록조회에 id변수 추가 및 컨트롤러, 서비스 수정
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubPostController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubPostListResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostServiceImpl.java
Labels: ✨ Feature

#154 포스트목록 수정 배포
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubPostController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubPostListResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubPostServiceImpl.java
Labels: ✨ Feature

#152 모임 수정 API 에러 재수정
  Inside-Out/src/main/java/com/goorm/insideout/meeting/controller/MeetingController.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/request/MeetingUpdateRequest.java
Labels: 🐞 Bug, 🚑 Emergency

#155 모임 수정 API 에러 재수정건 배포
  Inside-Out/src/main/java/com/goorm/insideout/meeting/controller/MeetingController.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/request/MeetingUpdateRequest.java
Labels: 🐞 Bug, 🚑 Emergency

#159 feat: 동아리 생성시 오류메세지 반환 추가
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubController.java
Labels: ✨ Feature

#162 fix: 클럽 엔티티 수정
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Club.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubApply.java
Labels: ✨ Feature

#170 fix: 동아리게시글댓글 api 수정
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubCommentController.java
Labels: ✨ Feature

#173 fix: 동아리 지원시 나이 계산 로직 수정
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubApplyServiceImpl.java
Labels: ✨ Feature

#189 fix: 클럽, 미팅 삭제시 채팅룸 삭제 기능 에러 수정
  Inside-Out/src/main/java/com/goorm/insideout/chatroom/domain/ChatRoom.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Club.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/domain/Meeting.java
Labels: ✨ Feature
