Repository Insideouuut/Insideouuut_backend, pull requests merged in 2024-07, with the labels that each got.

#6 develop브랜치 워크 플로우 설정
  .github/workflows/action-test.yml
Labels: 🌏 Infrastructure

#8 도커 이미지 빌드 및 자동 배포 구축
  .github/workflows/action-deploy.yml
Labels: 🌏 Infrastructure

#9 main 브랜치 배포 테스트
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/action-deploy.yml
  .github/workflows/action-test.yml
  Inside-Out/.gitignore
  Inside-Out/build.gradle
  Inside-Out/gradle/wrapper/gradle-wrapper.jar
  Inside-Out/gradle/wrapper/gradle-wrapper.properties
  Inside-Out/gradlew
  Inside-Out/gradlew.bat
  Inside-Out/settings.gradle
  Inside-Out/src/main/java/com/goorm/insideout/InsideOutApplication.java
  Inside-Out/src/test/java/com/goorm/insideout/InsideOutApplicationTests.java
Labels: 🌏 Infrastructure

#13 무중단 배포 테스트
  .github/workflows/action-deploy.yml
  Inside-Out/build.gradle
  script/deploy.sh
Labels: 🌏 Infrastructure

#14 스크립트 파일의 위치 정보 수정
  .github/workflows/action-deploy.yml
Labels: 🌏 Infrastructure

#16 배포 스크립트파일 읽기 경로 수정
  .github/workflows/action-deploy.yml
Labels: 🐞 Bug

#20 공통 API 응답 모델 구현
  Inside-Out/src/main/java/com/goorm/insideout/global/response/ApiResponse.java
Labels: ✨ Feature

#32 Feat/기본적인 동아리모임 검색 메서드 작성 #26
  Inside-Out/build.gradle
  Inside-Out/src/main/java/com/goorm/insideout/global/config/QueryDslConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/global/response/ApiResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/image/domain/Image.java
  Inside-Out/src/main/java/com/goorm/insideout/image/dto/response/ImageResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/like/domain/MeetingLike.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/domain/Category.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/domain/Level.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/domain/Meeting.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/request/MeetingSearchRequest.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/dto/response/MeetingResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/repository/MeetingRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/repository/custom/MeetingQueryDslRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/repository/custom/MeetingQueryDslRepositoryImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/meeting/service/MeetingService.java
  Inside-Out/src/main/java/com/goorm/insideout/search/controller/SearchController.java
Labels: ✨ Feature

#31 Feat/기본적인 채팅 구현 #28
  Inside-Out/build.gradle
  Inside-Out/src/main/java/com/goorm/insideout/chat/controller/ChatController.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/domain/Chat.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/dto/request/ChatRequestDTO.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/dto/response/ChatResponseDTO.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/repository/ChatRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/service/ChatService.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/websocket/WebSocketConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/websocket/WebSocketErrorHandler.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/websocket/WebSocketEventListener.java
  Inside-Out/src/main/java/com/goorm/insideout/chat/websocket/WebSocketInterceptor.java
  Inside-Out/src/main/java/com/goorm/insideout/chatroom/domain/ChatRoom.java
  Inside-Out/src/main/java/com/goorm/insideout/chatroom/domain/ChatRoomType.java
  Inside-Out/src/main/java/com/goorm/insideout/chatroom/repository/ChatRoomRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/global/exception/ErrorCode.java
Labels: ✨ Feature

#33 동아리 기본적인 crud 구현#30
  Inside-Out/src/main/java/com/goorm/insideout/auth/config/SecurityConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/club/controller/ClubController.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubBoardDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubDetail.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubDetailOwnerDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubDetailUserDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubInfo.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/ClubUserDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubDeleteRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubListRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/requestDto/ClubRequestDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubBoardResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubDetailResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubListResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubModifyResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/dto/responseDto/ClubResponseDto.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/Club.java
  Inside-Out/src/main/java/com/goorm/insideout/club/entity/ClubUser.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/repository/ClubUserRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserService.java
  Inside-Out/src/main/java/com/goorm/insideout/club/service/ClubUserServiceImpl.java
  Inside-Out/src/main/java/com/goorm/insideout/user/service/UserService.java
  Inside-Out/src/main/resources/application.properties
Labels: ✨ Feature

#37 Feature/카카오 로그인 구현#34
  Inside-Out/build.gradle
  Inside-Out/src/main/java/com/goorm/insideout/auth/config/SecurityConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/dto/CustomOAuth2User.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/dto/KakaoResponse.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/dto/OAuth2Response.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/dto/OAuth2UserDTO.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/filter/CustomOAuthLoginHandler.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/service/CustomOAuth2UserService.java
  Inside-Out/src/main/java/com/goorm/insideout/user/domain/User.java
Labels: ✨ Feature

#43 유저 프로필 및 회원가입시 관련 정보입력 기능 구현
  Inside-Out/src/main/java/com/goorm/insideout/auth/config/SecurityConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/filter/CustomOAuthLoginHandler.java
  Inside-Out/src/main/java/com/goorm/insideout/auth/utils/JWTUtil.java
  Inside-Out/src/main/java/com/goorm/insideout/global/config/CorsMvcConfig.java
  Inside-Out/src/main/java/com/goorm/insideout/user/controller/UserJoinController.java
  Inside-Out/src/main/java/com/goorm/insideout/user/domain/Gender.java
  Inside-Out/src/main/java/com/goorm/insideout/user/domain/User.java
  Inside-Out/src/main/java/com/goorm/insideout/user/dto/request/CheckEmailRequest.java
  Inside-Out/src/main/java/com/goorm/insideout/user/dto/request/CheckNicknameRequest.java
  Inside-Out/src/main/java/com/goorm/insideout/user/dto/request/SocialJoinRequest.java
  Inside-Out/src/main/java/com/goorm/insideout/user/dto/request/UserJoinRequestDTO.java
  Inside-Out/src/main/java/com/goorm/insideout/user/repository/UserRepository.java
  Inside-Out/src/main/java/com/goorm/insideout/user/service/UserJoinService.java
Labels: ✨ Feature
